# ワークフロー名
name: scrape-github-actions
on:
  push:
  schedule:
    # 定期実行する時間・・・①
    - cron: '0 8 * * *'

jobs:
  BSaction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - run: |
          pip install pandas
          pip install requests
          python scrape/scrape.py
